name: Deploy Landing Page

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Go to the specific service folder and pull new code
            cd /opt/hajat-app/services/HajatApp
            git pull origin main
            
            # 2. Go to infrastructure and rebuild ONLY the landing_page container
            cd /opt/hajat-app/infrastructure
            docker compose up -d --build landing_page
